### ISSUE TITLE
A bit confused with inputs for FitHiChIP

### ISSUE THREAD

**Issue by robeach78** [dovetail-genomics/HiChiP#1]
Hi I have run all the steps from HiChIP to HiC-pro and now I am approaching FitHiChIP.

What I dont seem to understand is all the inputs I need to place in FitHiChIP.

here is the results on a test of CTCF I have done and this is the output of FitHiChIP:

(base) ➜  FitHiChIP git:(master) ✗ ./FitHiChIP_HiCPro.sh -C example_config.txt  

 ================ Parsing input configuration file =================
Content of ValidPairs is /Users/RobertoFerrari/Downloads/HiC-Pro-master/CTCF/hic_results/data/sample1/HiChiP_CTCF_2M_hg38.bwt2pairs.validPairs.gz
Content of Interval is 
Content of Matrix is 
Content of Bed is 
Content of PeakFile is /Users/RobertoFerrari/Downloads/HiChiP/ENCFF017XLW.bed
Content of OutDir is /Users/RobertoFerrari/Downloads/fithichip_test_1kb
Content of IntType is 1
Content of BINSIZE is 2500
Content of LowDistThr is 20000
Content of UppDistThr is 2000000
Content of UseP2PBackgrnd is 0
Content of BiasType is 1
Content of MergeInt is 1
Content of QVALUE is 0.01
Content of ChrSizeFile is /Users/RobertoFerrari/Downloads/HiChiP/hg38.genome
Content of PREFIX is CTCF.DS.2.5kb
Content of OverWrite is 1
./FitHiChIP_HiCPro.sh: line 341: -12: substring expression < 0

 ================ Verifying input configuration parameters =================
ERROR ====>>> As user did not provide any pre-computed locus pairs (along with their contact count) in BED input, neither provided the HiC-pro base installation directory, FitHiChIP quits - exit !!

so what is this: pre-computed locus pairs (along with their contact count) in BED input?

and this: provided the HiC-pro base installation directory?

Thanks a lot for who can help me.

Best,
Roberto

**Comment by cpadillla1331** [comment]
Hi Roberto, 

Particular questions about running it should be directed to the authors of FitHiChIP: https://github.com/ay-lab/FitHiChIP
We just simply documented running a single example through that tool. 

That being noted there are a few things to point out:

1. The tutorial was written to use **./FitHiChIP_Docker.sh** not ./FitHiChIP_HiCPro.sh. The errors you received were because you did not provide the correct inputs to run FitHiChIP in that particular way. If you want to follow our tutorial please run with the docker shell script. Which would be a bedpe-like file of interactions and a path to the directory where HiC-Pro exists on your machine. To avoid this you can follow the tutorial and run the docker

2. It looks like you're using a bowtie2 based alignment - our tutorial is based on a BWA MEM alignment. Unless you trimmed the reads, there is going to be a lot of unaligned data because bowtie2 does not align the oligo-bridge sequence that we use to mediate proximity-ligation and incorporate biotin. Please check the alignment stats to make sure you're getting ~80% alignment rate

3. It also looks like you're using the 2 million read data set - this is likely to fail because there is not enough data. The FitHiChIP tutorial directs you to use the deeply sequenced CTCF (~400 M read pairs) to run the analyses. 

Hopefully, this is helpful, 
Cory
